package com.achpay.wallet.model.params;

public interface User {
    String TOKEN = "TOKEN";
    String MERCHANT_ID = "MERCHANT_ID";
    String MERCHANT_NAME = "MERCHANT_NAME";
    String SESSION_ID = "SESSION_ID";
    String ACH_SYS_ID = "MMKJ";
    String SYS_ID = "SYS_ID";
    String QFPAY_SYS_ID = "QFOAUTH";
    String QFPAY_SESSION_ID = "QFPAY_SESSION_ID";
    String QFPAY_MERCHANT_ID = "QFPAY_MERCHANT_ID";
    String QFPAY_SOURCE = "Near-Merchant-Android";

    //用户详情
    String SETTLE_ADDRESS = "SETTLE_ADDRESS";
    String SETTLE_AMOUNT = "SETTLE_AMOUNT";
    String SETTLE_PERIOD = "SETTLE_PERIOD";
    String SETTLE_TYPE = "SETTLE_TYPE";

    //order_id + status
    String LAST_ORDER_STATUS = "LAST_ORDER_STATUS";
    String LAST_ORDER_DETAIL = "LAST_ORDER_DETAIL";
    String LAST_ORDER_ISREAD = "LAST_ORDER_ISREAD";

    String SETTING_CRYPTOCURRENCY_ID = "SETTING_CRYPTOCURRENCY_ID";
    String SETTING_CRYPTOCURRENCY = "SETTING_CRYPTOCURRENCY";
    String SETTING_CURRENCY = "SETTING_CURRENCY";
    String SETTING_CURRENCY_UNIT = "SETTING_CURRENCY_UNIT";
    String SETTING_CURRENCY_ID = "SETTING_CURRENCY_ID";
    String SETTING_LANGUAGE = "SETTING_LANGUAGE";
    String SETTING_LANGUAGE_SELECTION = "SETTING_LANGUAGE_SELECTION";
    String SETTING_NETWORK = "SETTING_NETWORK";
    String SETTING_NETWORK_SELECTION = "SETTING_NETWORK_SELECTION";
    String OAUTH_STATE = "OAUTH_STATE";

    String TOTAL_COIN = "TOTAL_COIN";
    String TOTAL_CURRENCY = "TOTAL_CURRENCY";

    String SETTING_AMOUNT_TYPE = "SETTING_AMOUNT_TYPE";
    String SETTING_AMOUNT_DISCOUNT = "SETTING_AMOUNT_DISCOUNT";
    String SETTING_AMOUNT_EXTRA = "SETTING_AMOUNT_EXTRA";

    String DISCOUNT_TYPE = "DISCOUNT_TYPE";
    String DISCOUNT_CASH = "DISCOUNT_CASH";
    String DISCOUNT_PERCENT = "DISCOUNT_PERCENT";
    String DISCOUNT_CASH_AMOUNT = "DISCOUNT_CASH_AMOUNT";
    String DISCOUNT_PERCENT_AMOUNT = "DISCOUNT_PERCENT_AMOUNT";

    String EXTRA_TYPE = "EXTRA_TYPE";
    String EXTRA_CASH = "EXTRA_CASH";
    String EXTRA_PERCENT = "EXTRA_PERCENT";
    String EXTRA_CASH_AMOUNT = "EXTRA_CASH_AMOUNT";
    String EXTRA_PERCENT_AMOUNT = "EXTRA_PERCENT_AMOUNT";


    String DISCOUNT = "discount";
    String COUPON = "coupon";
    String POINTS = "points";
    String FIX = "fix";
    String TIP = "tip";

    String ADD = "add";
    String SUBTRACT = "subtract";

    String HISTORY_ORDER = "HISTORY_ORDER";
    String ORDER_ID = "ORDER_ID";

    String APP_HOST = "APP_HOST";
    String DEVICE_ID = "DEVICE_ID";

    String DOWNLOAD_ID = "DOWNLOAD_ID";
    String APK_MD5_VALUE = "APK_MD5_VALUE";
    String FIRST_TIME = "FIRST_TIME";
    String FILE_AUTHORITY = "com.achpay.wallet";

    String LOGIN_ACCESS_OAUTH = "LOGIN_ACCESS_OAUTH";
    String ACHPAY_LOGIN = "ACHPAY_LOGIN";
}
