/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_achpay_wallet_utils_NativeMethods */

#ifndef _Included_com_achpay_wallet_utils_NativeMethods
#define _Included_com_achpay_wallet_utils_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_achpay_wallet_utils_NativeMethods
 * Method:    getPWD
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_achpay_wallet_utils_NativeMethods_getPWD
  (JNIEnv *, jclass);

/*
 * Class:     com_achpay_wallet_utils_NativeMethods
 * Method:    getPWDSaltStart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_achpay_wallet_utils_NativeMethods_getPWDSaltStart
        (JNIEnv *, jclass);

/*
 * Class:     com_achpay_wallet_utils_NativeMethods
 * Method:    getPWDSaltEnd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_achpay_wallet_utils_NativeMethods_getPWDSaltEnd
        (JNIEnv *, jclass);

/*
 * Class:     com_achpay_wallet_utils_NativeMethods
 * Method:    getClientId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_achpay_wallet_utils_NativeMethods_getClientId
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
